# Generated by Django 5.0.7 on 2024-07-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblAccounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('activation_date', models.DateField()),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
