# Generated by Django 5.0.7 on 2024-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblaccounts',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
